### ISSUE TITLE
Loaded Pterodactyl Nest - Nothing Happens

### ISSUE THREAD

**Issue by drkthunder02** [ad3m3r5/TiltedEvolution-Docker#1]
Uploaded the pterodactyl egg, but no files seem to download to the pterodactyl panel.  Got 713 bytes of files after the installation script executed, when I am thinking there should be more files like on the order of at least a few hundred megabytes.  Let me know if I am doing anything wrong.

**Comment by ad3m3r5** [comment]
Once you upload the egg, which points to the public Docker image (ad3m3r5/tiltedevolution-pterodactyl), you can then create the server. The first time you start the server, it should pull the Docker image, which is about 95 MB unpacked. This contains the compiled project source. The only files that will be created within the Pterodactyl storage should be config files, which won't take up much space, since the project is contained within the image itself.

**Comment by r3in3r** [comment]
Can we add variables to the egg?

**Comment by ad3m3r5** [comment]
@r3in3r What variables are you referring to? The README mentions how to edit the STServer.ini config, which is a feature of TiltledEvolution.

**Comment by r3in3r** [comment]
the way the other eggs has vraibles see the image and json file ![variables](https://user-images.githubusercontent.com/21259511/221062916-18f29ad2-72f4-42c9-bb33-008fa66a5827.png)
"variables": [
        {
            "name": "Gold Loss Factor",
            "description": "Factor of the amount of gold lost on death",
            "env_variable": "CFG_GAME_GOLD_LOSS_FACTOR",
            "default_value": "0.0",
            "user_viewable": true,
            "user_editable": true,
            "rules": "required|numeric|max:1.0|min:0.0",
            "field_type": "text"
        },
        {
            "name": "Enable XP Sync",
            "description": "Syncs combat XP within the party",
            "env_variable": "CFG_GAME_XP_SYNC",
            "default_value": "1",
            "user_viewable": true,
            "user_editable": true,
            "rules": "required|boolean",
            "field_type": "text"
        },
        {
            "name": "Enable PVP",
            "description": "",
            "env_variable": "CFG_GAME_ENABLE_PVP",
            "default_value": "0",
            "user_viewable": true,
            "user_editable": true,
            "rules": "required|boolean",
            "field_type": "text"
        },
        {
            "name": "Enable Greetings",
            "description": "Enables NPC greetings (disabled by default since they can be spammy with dialogue sync)",
            "env_variable": "CFG_GAME_ENABLE_GREETINGS",
            "default_value": "0",
            "user_viewable": true,
            "user_editable": true,
            "rules": "required|boolean",
            "field_type": "text"
        },
        {
            "name": "Difficulty",
            "description": "In game difficulty",
            "env_variable": "CFG_GAME_DIFFICULTY",
            "default_value": "4",
            "user_viewable": true,
            "user_editable": true,
            "rules": "required|integer|min:0|max:5",
            "field_type": "text"
        },
        {
            "name": "Announce Server",
            "description": "Whether to list the server on the public server list",
            "env_variable": "CFG_LIVE_ANNOUNCE_SERVER",
            "default_value": "0",
            "user_viewable": true,
            "user_editable": true,
            "rules": "required|boolean",
            "field_type": "text"
        },
        {
            "name": "Allow MO2",
            "description": "Allow clients running Mod Organizer 2 to join",
            "env_variable": "CFG_MOD_ALLOW_MO2",
            "default_value": "1",
            "user_viewable": true,
            "user_editable": true,
            "rules": "required|boolean",
            "field_type": "text"
        },
        {
            "name": "Allow SKSE",
            "description": "Allow clients with SKSE active to join",
            "env_variable": "CFG_MOD_ALLOW_SKSE",
            "default_value": "1",
            "user_viewable": true,
            "user_editable": true,
            "rules": "required|boolean",
            "field_type": "text"
        },
        {
            "name": "Enable Mod Check",
            "description": "Enables the checking of mods on the server",
            "env_variable": "CFG_MOD_ENABLE_MOD_CHECK",
            "default_value": "0",
            "user_viewable": true,
            "user_editable": true,
            "rules": "required|boolean",
            "field_type": "text"
        },
        {
            "name": "Server Password",
            "description": "Set a password to join the server",
            "env_variable": "CFG_SRV_PASSWORD",
            "default_value": "",
            "user_viewable": true,
            "user_editable": true,
            "rules": "nullable|string|max:50",
            "field_type": "text"
        },
        {
            "name": "Server Name",
            "description": "Name that shows up in the server list. If empty, will be set to \"Private Server\".",
            "env_variable": "CFG_SRV_NAME",
            "default_value": "Dedicated Together Server",
            "user_viewable": true,
            "user_editable": true,
            "rules": "nullable|string|max:100",
            "field_type": "text"
        },
        {
            "name": "Premium Mode",
            "description": "Use premium tick rate",
            "env_variable": "CFG_SRV_PREMIUM_MODE",
            "default_value": "1",
            "user_viewable": true,
            "user_editable": true,
            "rules": "required|boolean",
            "field_type": "text"
        }
