### ISSUE TITLE
Pterodactyl Egg not updating to version 1.6.5

### ISSUE THREAD

**Issue by blackhat840** [ad3m3r5/TiltedEvolution-Docker#2]
It seems that the image is not updating to the latest version of Tilted Evolution version 1.6.5

**Comment by ad3m3r5** [comment]
@blackhat840 I have downgraded alpine back to 3.18 which solved the problem for now. Version 1.6.6 was published, but I will work to get the older ones published as well.

**Comment by blackhat840** [comment]
@ad3m3r5 Even when selecting 1.6.5, it installs 1.6.6 as the version and I can't connect in game.

**Comment by ad3m3r5** [comment]
It looks like I passed the wrong ARG name to the pterodactyl docker image when building. Testing and pushing fixes for 1.6.4 and 1.6.5 as they seem to be the only ones affected due to being built at a later time.

Thanks for finding that!

**Comment by ad3m3r5** [comment]
They should now be fixed alongside the latest tag which also got messed up.

I'm building 1.6.7 now and it should be automatically pushed when it's done.

**Comment by ad3m3r5** [comment]
1.6.7 has now been pushed and tags seemed to be fixed.
Thanks again @blackhat840 !
