### ISSUE TITLE
pterodactyl egg for Skyrim Together Reborn stopped working

### ISSUE THREAD

**Issue by PsYkE1977** [ad3m3r5/TiltedEvolution-Docker#3]
![afbeelding](https://github.com/user-attachments/assets/5b883eec-65c7-47cc-bdff-e2d1d91843ca)

I already edited the json file to edit 'ash' to 'bash'

now i get an error while installing the server in Pterodactyl in the entrypoint.sh

![afbeelding](https://github.com/user-attachments/assets/7c10bc24-cb50-4923-a5d5-80d7b072cf48)

**Comment by ad3m3r5** [comment]
I forgot that eggs don't automatically update and they overwrite /home/container. I just reverted to the original image layout and it appears to be fixed. Please pull the latest image and try again.

Thanks!

**Comment by PsYkE1977** [comment]
![image](https://github.com/user-attachments/assets/079910ea-a5be-40c4-be81-4f9f4130e3e4)

Thnx. It's working again.
