### ISSUE TITLE
Update mod version to 1.7.1

### ISSUE THREAD

**Issue by PeyPal** [ad3m3r5/TiltedEvolution-Docker#4]
A new update is available, 1.7.1. [https://www.nexusmods.com/skyrimspecialedition/mods/69993/?tab=files](https://www.nexusmods.com/skyrimspecialedition/mods/69993/?tab=files).

**Comment by ad3m3r5** [comment]
Hey @PeyPal, thanks for letting me know. I forgot to add my automation for it. Building 1.7.1 now and will run a build for 1.7.0 later
